export const FETCH_NEW_TIME = 'FETCH_NEW_TIME';
export const LOAD_POSTS_DATA = 'LOAD_POSTS_DATA';

export const API_CALL_REQUEST = "API_CALL_REQUEST";
export const API_CALL_SUCCESS = "API_CALL_SUCCESS";
export const API_CALL_FAILURE = "API_CALL_FAILURE";

export const OLYMPIC_API_CALL_REQUEST = "OLYMPIC_API_CALL_REQUEST";
export const OLYMPIC_API_CALL_SUCCESS = "OLYMPIC_API_CALL_SUCCESS";
export const OLYMPIC_API_CALL_FAILURE = "OLYMPIC_API_CALL_FAILURE";

export const FORM_SUBMIT = "FORM_SUBMIT";

export const SELECT_CHANNEL_NEWS = "SELECT_CHANNEL_NEWS";
export const CHANNEL_NEWS_API_CALL_REQUEST = "CHANNEL_NEWS_API_CALL_REQUEST";
export const CHANNEL_NEWS_API_CALL_SUCCESS = "CHANNEL_NEWS_API_CALL_SUCCESS";
export const CHANNEL_NEWS_API_CALL_FAILURE = "CHANNEL_NEWS_API_CALL_FAILURE";

export const GET_USERS_DATA = 'GET_USERS_DATA';
export const GET_USER_DATA = 'GET_USER_DATA';
export const UPDATE_USER = 'UPDATE_USER';
export const ADD_NEW_USER = 'ADD_NEW_USER';

export const LOADING_NEWS = 'LOADING_NEWS';
export const FETCH_NEWS = 'FETCH_NEWS';

export const PIE_CHART = 'PIE_CHART';


export const ABN_NEWS_API_CALL_REQUEST = "ABN_NEWS_API_CALL_REQUEST";
export const ABN_NEWS_API_CALL_SUCCESS = "ABN_NEWS_API_CALL_SUCCESS";
export const ABN_NEWS_API_CALL_FAILURE = "ABN_NEWS_API_CALL_FAILURE";
export const ABN_NEWS_DETAILS = "ABN_NEWS_DETAILS";


export const LOAD_ALL_USERS = "LOAD_ALL_USERS";
export const FILTER_BY_VALUE = "FILTER_BY_VALUE";
export const FILTER_USERS = "FILTER_USERS";

export const SEARCH_OLYMPICS = "SEARCH_OLYMPICS";
export const CHART_OPTIONS = "CHART_OPTIONS";
export const SHOW_PANE = "SHOW_PANE";
export const SHOW_ROW_DETAILS = "SHOW_ROW_DETAILS";




